---
kind: pipeline
type: docker
name: get updates

steps:
- name: test push
  image: alpine
  commands:
  - echo update triggered

trigger:
  event:
  - cron
  cron:
  - minutely

---
kind: pipeline
type: docker
name: promote

steps:
- name: test promote
  image: alpine
  commands:
  - echo promote triggered

trigger:
  event:
  - promote
