kind: pipeline
type: docker
name: default
   
steps:
- name: test push
  image: alpine
  commands:
  - echo push triggered
  trigger:
    event:
    - push
- name: test promote
  image: alpine
  commands:
  - echo promote triggered
  trigger:
    event:
    - promote
